### ISSUE TITLE
Broken application build

### ISSUE THREAD

**Issue by vold4** [stardustxx/vue3-starter#14]
Hi, do you have experience with building an application through your script? Unfortunately, I can't list a working build, including html. Thank you for answer

**Comment by stardustxx** [comment]
Hey sorry for super late reply, did you have any luck?

**Comment by vold4** [comment]
Thanks for the reply, but unfortunately I was unable to resolve this issue. Basically when I do build even just the source file can't run. Did it work for you?

**Comment by stardustxx** [comment]
Do you have a sample project maybe we can take a look?
Details of what you are trying to do?

I just updated my repo to use Vite instead of Webpack now maybe give that a try if that works for your particular case?
Or if all fail try using Vite with their sample template?

I'm just listing out all of the possible options here

**Comment by stardustxx** [comment]
Closing for now. Please open a new issue if problem persists
